language: erlang
otp_release:
  - 19.3.6.1
before_install:
  - ./ci before_install "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
install:
  - ./ci install "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
script:
  - ./ci script "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
after_failure:
  - ./ci after_failure "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
matrix:
  include:
    - language: erlang
      otp_release: 20.0.1
      env: JOB=tests
    - language: erlang
      otp_release: 18.3
      env: JOB=tests
  allow_failures:
    - language: erlang
      otp_release: 20.0.1 ## Delete this allowed failure when tests are stable.
      env: JOB=tests
    - language: erlang
      otp_release: 18.3 ## Delete this allowed failure when tests are stable.
      env: JOB=tests
    - env: JOB=unit-tests
    - env: JOB=dialyzer
    - env: JOB=xref
  fast_finish: true
env:
  - JOB=swagger
  - JOB=tests
  - JOB=tester
  - JOB=unit-tests
  - JOB=dialyzer
  - JOB=xref
cache:
  directories:
    - $HOME/.cache/rebar3
